export const currencyLists = [
  { name: "Afghan Afghani", countryName: "Afghanistan", symbol: "AFN" },
  { name: "Euro", countryName: "Albania", symbol: "€" },
  { name: "Albanian Lek", countryName: "Albania", symbol: "ALL" },
  { name: "Algerian Dinar", countryName: "Algeria", symbol: "DZD" },
  { name: "Angolan Kwanza", countryName: "Angola", symbol: "AOA" },
  {
    name: "East Caribbean Dollar",
    countryName: "Antigua and Barbuda",
    symbol: "XCD",
  },
  { name: "Argentine Peso", countryName: "Argentina", symbol: "ARS" },
  { name: "Armenian Dram", countryName: "Armenia", symbol: "AMD" },
  { name: "Australian Dollar", countryName: "Australia", symbol: "A$" },
  { name: "Azerbaijani Manat", countryName: "Azerbaijan", symbol: "AZN" },
  { name: "Bahamian Dollar", countryName: "Bahamas", symbol: "BSD" },
  { name: "Bahraini Dinar", countryName: "Bahrain", symbol: "BHD" },
  { name: "Bangladeshi Taka", countryName: "Bangladesh", symbol: "BDT" },
  { name: "Barbadian Dollar", countryName: "Barbados", symbol: "BBD" },
  { name: "Belarusian Ruble", countryName: "Belarus", symbol: "BYN" },
  { name: "Belize Dollar", countryName: "Belize", symbol: "BZD" },
  { name: "West African CFA Franc", countryName: "Benin", symbol: "XOF" },
  { name: "Bermudian Dollar", countryName: "Bermuda", symbol: "BMD" },
  { name: "Bhutanese Ngultrum", countryName: "Bhutan", symbol: "BTN" },
  { name: "Bolivian Boliviano", countryName: "Bolivia", symbol: "BOB" },
  {
    name: "Bosnia and Herzegovina Convertible Mark",
    countryName: "Bosnia and Herzegovina",
    symbol: "BAM",
  },
  { name: "Botswana Pula", countryName: "Botswana", symbol: "BWP" },
  { name: "Brazilian Real", countryName: "Brazil", symbol: "BRL" },
  { name: "Brunei Dollar", countryName: "Brunei", symbol: "BND" },
  { name: "Bulgarian Lev", countryName: "Bulgaria", symbol: "BGN" },
  { name: "Burundian Franc", countryName: "Burundi", symbol: "BIF" },
  { name: "Cabo Verdean Escudo", countryName: "Cabo Verde", symbol: "CVE" },
  { name: "Cambodian Riel", countryName: "Cambodia", symbol: "KHR" },
  { name: "Canadian Dollar", countryName: "Canada", symbol: "C$" },
  {
    name: "Central African CFA Franc",
    countryName: "Central African Republic",
    symbol: "XAF",
  },
  { name: "Chilean Peso", countryName: "Chile", symbol: "CLP" },
  { name: "Chinese Yuan", countryName: "China", symbol: "¥" },
  { name: "Colombian Peso", countryName: "Colombia", symbol: "COP" },
  { name: "Comorian Franc", countryName: "Comoros", symbol: "KMF" },
  {
    name: "Congolese Franc",
    countryName: "Democratic Republic of the Congo",
    symbol: "CDF",
  },
  { name: "Costa Rican Colón", countryName: "Costa Rica", symbol: "CRC" },
  { name: "Croatian Kuna", countryName: "Croatia", symbol: "HRK" },
  { name: "Cuban Peso", countryName: "Cuba", symbol: "CUP" },
  { name: "Czech Koruna", countryName: "Czech Republic", symbol: "CZK" },
  { name: "Danish Krone", countryName: "Denmark", symbol: "DKK" },
  { name: "Djiboutian Franc", countryName: "Djibouti", symbol: "DJF" },
  { name: "Dominican Peso", countryName: "Dominican Republic", symbol: "DOP" },
  { name: "Egyptian Pound", countryName: "Egypt", symbol: "EGP" },
  { name: "El Salvadoran Colón", countryName: "El Salvador", symbol: "SVC" },
  {
    name: "Equatorial Guinean CFA Franc",
    countryName: "Equatorial Guinea",
    symbol: "XAF",
  },
  { name: "Eritrean Nakfa", countryName: "Eritrea", symbol: "ERN" },
  { name: "Estonian Kroon", countryName: "Estonia", symbol: "EEK" },
  { name: "Ethiopian Birr", countryName: "Ethiopia", symbol: "ETB" },
  { name: "Fijian Dollar", countryName: "Fiji", symbol: "FJD" },
  {
    name: "Falkland Islands Pound",
    countryName: "Falkland Islands",
    symbol: "FKP",
  },
  { name: "Gambian Dalasi", countryName: "Gambia", symbol: "GMD" },
  { name: "Georgian Lari", countryName: "Georgia", symbol: "GEL" },
  { name: "Ghanaian Cedi", countryName: "Ghana", symbol: "GHS" },
  { name: "Gibraltar Pound", countryName: "Gibraltar", symbol: "GIP" },
  { name: "Greek Euro", countryName: "Greece", symbol: "€" },
  { name: "Grenadian Dollar", countryName: "Grenada", symbol: "XCD" },
  { name: "Guatemalan Quetzal", countryName: "Guatemala", symbol: "GTQ" },
  { name: "Guinean Franc", countryName: "Guinea", symbol: "GNF" },
  { name: "Guyanese Dollar", countryName: "Guyana", symbol: "GYD" },
  { name: "Haitian Gourde", countryName: "Haiti", symbol: "HTG" },
  { name: "Honduran Lempira", countryName: "Honduras", symbol: "HNL" },
  { name: "Hungarian Forint", countryName: "Hungary", symbol: "HUF" },
  { name: "Icelandic Króna", countryName: "Iceland", symbol: "ISK" },
  { name: "Indian Rupee", countryName: "India", symbol: "₹" },
  { name: "Indonesian Rupiah", countryName: "Indonesia", symbol: "IDR" },
  { name: "Iranian Rial", countryName: "Iran", symbol: "IRR" },
  { name: "Iraqi Dinar", countryName: "Iraq", symbol: "IQD" },
  { name: "Israeli New Shekel", countryName: "Israel", symbol: "₪" },
  { name: "Italian Euro", countryName: "Italy", symbol: "€" },
  { name: "Jamaican Dollar", countryName: "Jamaica", symbol: "JMD" },
  { name: "Japanese Yen", countryName: "Japan", symbol: "¥" },
  { name: "Jordanian Dinar", countryName: "Jordan", symbol: "JOD" },
  { name: "Kazakhstani Tenge", countryName: "Kazakhstan", symbol: "KZT" },
  { name: "Kenyan Shilling", countryName: "Kenya", symbol: "KES" },
  { name: "Kiribati Dollar", countryName: "Kiribati", symbol: "AUD" },
  { name: "Kuwaiti Dinar", countryName: "Kuwait", symbol: "KWD" },
  { name: "Kyrgyzstani Som", countryName: "Kyrgyzstan", symbol: "KGS" },
  { name: "Lao Kip", countryName: "Laos", symbol: "LAK" },
  { name: "Latvian Lats", countryName: "Latvia", symbol: "LVL" },
  { name: "Lebanese Pound", countryName: "Lebanon", symbol: "LBP" },
  { name: "Lesotho Loti", countryName: "Lesotho", symbol: "LSL" },
  { name: "Liberian Dollar", countryName: "Liberia", symbol: "LRD" },
  { name: "Libyan Dinar", countryName: "Libya", symbol: "LYD" },
  {
    name: "Liechtenstein Swiss Franc",
    countryName: "Liechtenstein",
    symbol: "CHF",
  },
  { name: "Lithuanian Litas", countryName: "Lithuania", symbol: "LTL" },
  { name: "Luxembourg Euro", countryName: "Luxembourg", symbol: "€" },
  { name: "Macanese Pataca", countryName: "Macau", symbol: "MOP" },
  { name: "Madagascan Ariary", countryName: "Madagascar", symbol: "MGA" },
  { name: "Malawian Kwacha", countryName: "Malawi", symbol: "MWK" },
  { name: "Malaysian Ringgit", countryName: "Malaysia", symbol: "MYR" },
  { name: "Maldivian Rufiyaa", countryName: "Maldives", symbol: "MVR" },
  { name: "Mali CFA Franc", countryName: "Mali", symbol: "XOF" },
  { name: "Mauritanian Ouguiya", countryName: "Mauritania", symbol: "MRU" },
  { name: "Mauritian Rupee", countryName: "Mauritius", symbol: "MUR" },
  { name: "Mexican Peso", countryName: "Mexico", symbol: "MXN" },
  { name: "Micronesian Dollar", countryName: "Micronesia", symbol: "USD" },
  { name: "Moldovan Leu", countryName: "Moldova", symbol: "MDL" },
  { name: "Mongolian Tugrik", countryName: "Mongolia", symbol: "MNT" },
  { name: "Moroccan Dirham", countryName: "Morocco", symbol: "MAD" },
  { name: "Mozambican Metical", countryName: "Mozambique", symbol: "MZN" },
  { name: "Myanmar Kyat", countryName: "Myanmar", symbol: "MMK" },
  { name: "Namibian Dollar", countryName: "Namibia", symbol: "NAD" },
  { name: "Nauruan Dollar", countryName: "Nauru", symbol: "AUD" },
  { name: "Nepalese Rupee", countryName: "Nepal", symbol: "NPR" },
  {
    name: "Netherlands Antillean Guilder",
    countryName: "Netherlands Antilles",
    symbol: "ANG",
  },
  { name: "New Zealand Dollar", countryName: "New Zealand", symbol: "NZ$" },
  { name: "Nigerian Naira", countryName: "Nigeria", symbol: "NGN" },
  { name: "North Korean Won", countryName: "North Korea", symbol: "KPW" },
  { name: "Norwegian Krone", countryName: "Norway", symbol: "NOK" },
  { name: "Omani Rial", countryName: "Oman", symbol: "OMR" },
  { name: "Pakistani Rupee", countryName: "Pakistan", symbol: "PKR" },
  { name: "Palauan Dollar", countryName: "Palau", symbol: "USD" },
  { name: "Panamanian Balboa", countryName: "Panama", symbol: "PAB" },
  {
    name: "Papua New Guinean Kina",
    countryName: "Papua New Guinea",
    symbol: "PGK",
  },
  { name: "Paraguayan Guarani", countryName: "Paraguay", symbol: "PYG" },
  { name: "Peruvian Nuevo Sol", countryName: "Peru", symbol: "PEN" },
  { name: "Philippine Peso", countryName: "Philippines", symbol: "PHP" },
  { name: "Polish Zloty", countryName: "Poland", symbol: "PLN" },
  { name: "Portuguese Euro", countryName: "Portugal", symbol: "€" },
  { name: "Qatari Rial", countryName: "Qatar", symbol: "QAR" },
  { name: "Romanian Leu", countryName: "Romania", symbol: "RON" },
  { name: "Russian Ruble", countryName: "Russia", symbol: "₽" },
  { name: "Rwandan Franc", countryName: "Rwanda", symbol: "RWF" },
  {
    name: "Saint Kitts and Nevis Dollar",
    countryName: "Saint Kitts and Nevis",
    symbol: "XCD",
  },
  { name: "Saint Lucian Dollar", countryName: "Saint Lucia", symbol: "XCD" },
  {
    name: "Saint Vincent and the Grenadines Dollar",
    countryName: "Saint Vincent and the Grenadines",
    symbol: "XCD",
  },
  { name: "Samoan Tala", countryName: "Samoa", symbol: "WST" },
  {
    name: "San Marinese Sammarinese Lira",
    countryName: "San Marino",
    symbol: "SML",
  },
  {
    name: "São Tomé and Príncipe Dobra",
    countryName: "São Tomé and Príncipe",
    symbol: "STN",
  },
  { name: "Saudi Riyal", countryName: "Saudi Arabia", symbol: "SAR" },
  { name: "Scottish Pound", countryName: "Scotland", symbol: "£" },
  { name: "Serbian Dinar", countryName: "Serbia", symbol: "RSD" },
  { name: "Seychellois Rupee", countryName: "Seychelles", symbol: "SCR" },
  { name: "Sierra Leonean Leone", countryName: "Sierra Leone", symbol: "SLL" },
  { name: "Singapore Dollar", countryName: "Singapore", symbol: "S$" },
  { name: "Slovak Euro", countryName: "Slovakia", symbol: "€" },
  { name: "Slovenian Euro", countryName: "Slovenia", symbol: "€" },
  {
    name: "Solomon Islands Dollar",
    countryName: "Solomon Islands",
    symbol: "SBD",
  },
  { name: "Somali Shilling", countryName: "Somalia", symbol: "SOS" },
  { name: "South African Rand", countryName: "South Africa", symbol: "ZAR" },
  { name: "South Sudanese Pound", countryName: "South Sudan", symbol: "SSP" },
  { name: "Spanish Euro", countryName: "Spain", symbol: "€" },
  { name: "Sri Lankan Rupee", countryName: "Sri Lanka", symbol: "LKR" },
  { name: "Sudanese Pound", countryName: "Sudan", symbol: "SDG" },
  { name: "Surinamese Dollar", countryName: "Suriname", symbol: "SRD" },
  { name: "Swedish Krona", countryName: "Sweden", symbol: "SEK" },
  { name: "Swiss Franc", countryName: "Switzerland", symbol: "CHF" },
  { name: "Syrian Pound", countryName: "Syria", symbol: "SYP" },
  { name: "Taiwan Dollar", countryName: "Taiwan", symbol: "TWD" },
  { name: "Tajikistani Somoni", countryName: "Tajikistan", symbol: "TJS" },
  { name: "Tanzanian Shilling", countryName: "Tanzania", symbol: "TZS" },
  { name: "Thai Baht", countryName: "Thailand", symbol: "THB" },
  { name: "Timorese Dollar", countryName: "Timor-Leste", symbol: "USD" },
  { name: "Tongan Paʻanga", countryName: "Tonga", symbol: "TOP" },
  {
    name: "Trinidad and Tobago Dollar",
    countryName: "Trinidad and Tobago",
    symbol: "TTD",
  },
  { name: "Tunisian Dinar", countryName: "Tunisia", symbol: "TND" },
  { name: "Turkish Lira", countryName: "Turkey", symbol: "₺" },
  { name: "Turkmenistani Manat", countryName: "Turkmenistan", symbol: "TMT" },
  { name: "Tuvaluan Dollar", countryName: "Tuvalu", symbol: "AUD" },
  { name: "Ugandan Shilling", countryName: "Uganda", symbol: "UGX" },
  { name: "Ukrainian Hryvnia", countryName: "Ukraine", symbol: "UAH" },
  {
    name: "United Arab Emirates Dirham",
    countryName: "United Arab Emirates",
    symbol: "AED",
  },
  { name: "United States Dollar", countryName: "United States", symbol: "USD" },
  { name: "Uruguayan Peso", countryName: "Uruguay", symbol: "UYU" },
  { name: "Uzbekistani Som", countryName: "Uzbekistan", symbol: "UZS" },
  { name: "Vanuatu Vatu", countryName: "Vanuatu", symbol: "VUV" },
  { name: "Venezuelan Bolívar", countryName: "Venezuela", symbol: "VES" },
  { name: "Vietnamese Dong", countryName: "Vietnam", symbol: "VND" },
  { name: "Yemeni Rial", countryName: "Yemen", symbol: "YER" },
  { name: "Zambian Kwacha", countryName: "Zambia", symbol: "ZMW" },
  { name: "Zimbabwean Dollar", countryName: "Zimbabwe", symbol: "ZWL" },
];

export const languageList = [
  { countryCode: "AF", name: "Pashto" },
  { countryCode: "AF", name: "Dari" },
  { countryCode: "AL", name: "Albanian" },
  { countryCode: "DZ", name: "Arabic" },
  { countryCode: "AO", name: "Portuguese" },
  { countryCode: "AG", name: "English" },
  { countryCode: "AR", name: "Spanish" },
  { countryCode: "AM", name: "Armenian" },
  { countryCode: "AU", name: "English" },
  { countryCode: "AZ", name: "Azerbaijani" },
  { countryCode: "BS", name: "English" },
  { countryCode: "BH", name: "Arabic" },
  { countryCode: "BD", name: "Bengali" },
  { countryCode: "BB", name: "English" },
  { countryCode: "BY", name: "Belarusian" },
  { countryCode: "BY", name: "Russian" },
  { countryCode: "BZ", name: "English" },
  { countryCode: "BJ", name: "French" },
  { countryCode: "BM", name: "English" },
  { countryCode: "BT", name: "Dzongkha" },
  { countryCode: "BO", name: "Spanish" },
  { countryCode: "BO", name: "Quechua" },
  { countryCode: "BA", name: "Bosnian" },
  { countryCode: "BA", name: "Croatian" },
  { countryCode: "BA", name: "Serbian" },
  { countryCode: "BW", name: "Tswana" },
  { countryCode: "BR", name: "Portuguese" },
  { countryCode: "BN", name: "Malay" },
  { countryCode: "BG", name: "Bulgarian" },
  { countryCode: "BF", name: "French" },
  { countryCode: "BI", name: "Kirundi" },
  { countryCode: "BI", name: "French" },
  { countryCode: "CV", name: "Portuguese" },
  { countryCode: "KH", name: "Khmer" },
  { countryCode: "CA", name: "English" },
  { countryCode: "CA", name: "French" },
  { countryCode: "CF", name: "French" },
  { countryCode: "CF", name: "Sango" },
  { countryCode: "CL", name: "Spanish" },
  { countryCode: "CN", name: "Mandarin" },
  { countryCode: "CO", name: "Spanish" },
  { countryCode: "KM", name: "Comorian" },
  { countryCode: "KM", name: "Arabic" },
  { countryCode: "CD", name: "French" },
  { countryCode: "CD", name: "Lingala" },
  { countryCode: "CR", name: "Spanish" },
  { countryCode: "HR", name: "Croatian" },
  { countryCode: "CU", name: "Spanish" },
  { countryCode: "CZ", name: "Czech" },
  { countryCode: "DK", name: "Danish" },
  { countryCode: "DJ", name: "Arabic" },
  { countryCode: "DJ", name: "French" },
  { countryCode: "DO", name: "Spanish" },
  { countryCode: "EG", name: "Arabic" },
  { countryCode: "SV", name: "Spanish" },
  { countryCode: "GQ", name: "Spanish" },
  { countryCode: "GQ", name: "French" },
  { countryCode: "GQ", name: "Portuguese" },
  { countryCode: "ER", name: "Tigrinya" },
  { countryCode: "ER", name: "Arabic" },
  { countryCode: "EE", name: "Estonian" },
  { countryCode: "ET", name: "Amharic" },
  { countryCode: "FJ", name: "Fijian" },
  { countryCode: "FJ", name: "English" },
  { countryCode: "FK", name: "English" },
  { countryCode: "FM", name: "English" },
  { countryCode: "GA", name: "French" },
  { countryCode: "GM", name: "English" },
  { countryCode: "GE", name: "Georgian" },
  { countryCode: "GH", name: "English" },
  { countryCode: "GI", name: "English" },
  { countryCode: "GR", name: "Greek" },
  { countryCode: "GD", name: "English" },
  { countryCode: "GT", name: "Spanish" },
  { countryCode: "GU", name: "English" },
  { countryCode: "GW", name: "Portuguese" },
  { countryCode: "GY", name: "English" },
  { countryCode: "HT", name: "Haitian Creole" },
  { countryCode: "HT", name: "French" },
  { countryCode: "HN", name: "Spanish" },
  { countryCode: "HU", name: "Hungarian" },
  { countryCode: "IS", name: "Icelandic" },
  { countryCode: "IN", name: "Hindi" },
  { countryCode: "IN", name: "English" },
  { countryCode: "ID", name: "Indonesian" },
  { countryCode: "IR", name: "Persian" },
  { countryCode: "IQ", name: "Arabic" },
  { countryCode: "IL", name: "Hebrew" },
  { countryCode: "IT", name: "Italian" },
  { countryCode: "JM", name: "English" },
  { countryCode: "JP", name: "Japanese" },
  { countryCode: "JO", name: "Arabic" },
  { countryCode: "KZ", name: "Kazakh" },
  { countryCode: "KZ", name: "Russian" },
  { countryCode: "KE", name: "Swahili" },
  { countryCode: "KE", name: "English" },
  { countryCode: "KI", name: "English" },
  { countryCode: "KI", name: "Gilbertese" },
  { countryCode: "KW", name: "Arabic" },
  { countryCode: "KG", name: "Kyrgyz" },
  { countryCode: "KG", name: "Russian" },
  { countryCode: "LA", name: "Lao" },
  { countryCode: "LV", name: "Latvian" },
  { countryCode: "LB", name: "Arabic" },
  { countryCode: "LS", name: "Sesotho" },
  { countryCode: "LR", name: "English" },
  { countryCode: "LY", name: "Arabic" },
  { countryCode: "LI", name: "German" },
  { countryCode: "LT", name: "Lithuanian" },
  { countryCode: "LU", name: "Luxembourgish" },
  { countryCode: "LU", name: "French" },
  { countryCode: "LU", name: "German" },
  { countryCode: "MO", name: "Chinese" },
  { countryCode: "MO", name: "Portuguese" },
  { countryCode: "MG", name: "Malagasy" },
  { countryCode: "MG", name: "French" },
  { countryCode: "MW", name: "Chichewa" },
  { countryCode: "MW", name: "English" },
  { countryCode: "MY", name: "Malay" },
  { countryCode: "MV", name: "Dhivehi" },
  { countryCode: "ML", name: "Bambara" },
  { countryCode: "ML", name: "French" },
  { countryCode: "MR", name: "Arabic" },
  { countryCode: "MR", name: "Pulaar" },
  { countryCode: "MU", name: "English" },
  { countryCode: "MU", name: "French" },
  { countryCode: "MX", name: "Spanish" },
  { countryCode: "FM", name: "English" },
  { countryCode: "MD", name: "Romanian" },
  { countryCode: "MN", name: "Mongolian" },
  { countryCode: "MA", name: "Arabic" },
  { countryCode: "MA", name: "Berber" },
  { countryCode: "MZ", name: "Portuguese" },
  { countryCode: "MM", name: "Burmese" },
  { countryCode: "NA", name: "English" },
  { countryCode: "NA", name: "Afrikaans" },
  { countryCode: "NP", name: "Nepali" },
  { countryCode: "NL", name: "Dutch" },
  { countryCode: "NL", name: "Frisian" },
  { countryCode: "NC", name: "French" },
  { countryCode: "NZ", name: "English" },
  { countryCode: "NG", name: "English" },
  { countryCode: "KP", name: "Korean" },
  { countryCode: "KR", name: "Korean" },
  { countryCode: "NO", name: "Norwegian" },
  { countryCode: "OM", name: "Arabic" },
  { countryCode: "PK", name: "Urdu" },
  { countryCode: "PK", name: "English" },
  { countryCode: "PW", name: "English" },
  { countryCode: "PA", name: "Spanish" },
  { countryCode: "PA", name: "Panamanian Spanish" },
  { countryCode: "PG", name: "Hiri Motu" },
  { countryCode: "PG", name: "Tok Pisin" },
  { countryCode: "PY", name: "Spanish" },
  { countryCode: "PY", name: "Guaraní" },
  { countryCode: "PE", name: "Spanish" },
  { countryCode: "PE", name: "Quechua" },
  { countryCode: "PH", name: "Filipino" },
  { countryCode: "PH", name: "English" },
  { countryCode: "PL", name: "Polish" },
  { countryCode: "PT", name: "Portuguese" },
  { countryCode: "QA", name: "Arabic" },
  { countryCode: "RO", name: "Romanian" },
  { countryCode: "RU", name: "Russian" },
  { countryCode: "RW", name: "Kinyarwanda" },
  { countryCode: "RW", name: "French" },
  { countryCode: "KN", name: "English" },
  { countryCode: "LC", name: "English" },
  { countryCode: "VC", name: "English" },
  { countryCode: "WS", name: "Samoan" },
  { countryCode: "SM", name: "Italian" },
  { countryCode: "ST", name: "Portuguese" },
  { countryCode: "SA", name: "Arabic" },
  { countryCode: "SC", name: "Seychellois Creole" },
  { countryCode: "SC", name: "French" },
  { countryCode: "SC", name: "English" },
  { countryCode: "SL", name: "English" },
  { countryCode: "SG", name: "English" },
  { countryCode: "SG", name: "Mandarin" },
  { countryCode: "SG", name: "Malay" },
  { countryCode: "SG", name: "Tamil" },
  { countryCode: "SK", name: "Slovak" },
  { countryCode: "SI", name: "Slovenian" },
  { countryCode: "SB", name: "Solomon Islands Pidgin" },
  { countryCode: "SO", name: "Somali" },
  { countryCode: "SO", name: "Arabic" },
  { countryCode: "ZA", name: "Afrikaans" },
  { countryCode: "ZA", name: "English" },
  { countryCode: "ZA", name: "Zulu" },
  { countryCode: "ZA", name: "Xhosa" },
  { countryCode: "SS", name: "English" },
  { countryCode: "SS", name: "Arabic" },
  { countryCode: "ES", name: "Spanish" },
  { countryCode: "LK", name: "Sinhala" },
  { countryCode: "LK", name: "Tamil" },
  { countryCode: "SD", name: "Arabic" },
  { countryCode: "SR", name: "Dutch" },
  { countryCode: "SV", name: "Spanish" },
  { countryCode: "SE", name: "Swedish" },
  { countryCode: "CH", name: "German" },
  { countryCode: "CH", name: "French" },
  { countryCode: "CH", name: "Italian" },
  { countryCode: "CH", name: "Romansh" },
  { countryCode: "SY", name: "Arabic" },
  { countryCode: "TW", name: "Mandarin" },
  { countryCode: "TJ", name: "Tajik" },
  { countryCode: "TZ", name: "Swahili" },
  { countryCode: "TZ", name: "English" },
  { countryCode: "TH", name: "Thai" },
  { countryCode: "TL", name: "Tetum" },
  { countryCode: "TL", name: "Portuguese" },
  { countryCode: "TO", name: "Tongan" },
  { countryCode: "TT", name: "English" },
  { countryCode: "TN", name: "Arabic" },
  { countryCode: "TR", name: "Turkish" },
  { countryCode: "TM", name: "Turkmen" },
  { countryCode: "TV", name: "Tuvaluan" },
  { countryCode: "UG", name: "English" },
  { countryCode: "UG", name: "Luganda" },
  { countryCode: "UA", name: "Ukrainian" },
  { countryCode: "AE", name: "Arabic" },
  { countryCode: "US", name: "English" },
  { countryCode: "UY", name: "Spanish" },
  { countryCode: "UZ", name: "Uzbek" },
  { countryCode: "VU", name: "Bislama" },
  { countryCode: "VU", name: "English" },
  { countryCode: "VU", name: "French" },
  { countryCode: "VE", name: "Spanish" },
  { countryCode: "VN", name: "Vietnamese" },
  { countryCode: "YE", name: "Arabic" },
  { countryCode: "ZM", name: "English" },
  { countryCode: "ZW", name: "English" },
  { countryCode: "ZW", name: "Shona" },
  { countryCode: "ZW", name: "Sindebele" },
];

export const phoneCodesList = [
  { countryCode: "AF", phoneCode: "+93", countryName: "Afghanistan" },
  { countryCode: "AL", phoneCode: "+355", countryName: "Albania" },
  { countryCode: "DZ", phoneCode: "+213", countryName: "Algeria" },
  { countryCode: "AD", phoneCode: "+376", countryName: "Andorra" },
  { countryCode: "AO", phoneCode: "+244", countryName: "Angola" },
  {
    countryCode: "AG",
    phoneCode: "+1-268",
    countryName: "Antigua and Barbuda",
  },
  { countryCode: "AR", phoneCode: "+54", countryName: "Argentina" },
  { countryCode: "AM", phoneCode: "+374", countryName: "Armenia" },
  { countryCode: "AU", phoneCode: "+61", countryName: "Australia" },
  { countryCode: "AT", phoneCode: "+43", countryName: "Austria" },
  { countryCode: "AZ", phoneCode: "+994", countryName: "Azerbaijan" },
  { countryCode: "BS", phoneCode: "+1-242", countryName: "Bahamas" },
  { countryCode: "BH", phoneCode: "+973", countryName: "Bahrain" },
  { countryCode: "BD", phoneCode: "+880", countryName: "Bangladesh" },
  { countryCode: "BB", phoneCode: "+1-246", countryName: "Barbados" },
  { countryCode: "BY", phoneCode: "+375", countryName: "Belarus" },
  { countryCode: "BE", phoneCode: "+32", countryName: "Belgium" },
  { countryCode: "BZ", phoneCode: "+501", countryName: "Belize" },
  { countryCode: "BJ", phoneCode: "+229", countryName: "Benin" },
  { countryCode: "BT", phoneCode: "+975", countryName: "Bhutan" },
  { countryCode: "BO", phoneCode: "+591", countryName: "Bolivia" },
  {
    countryCode: "BA",
    phoneCode: "+387",
    countryName: "Bosnia and Herzegovina",
  },
  { countryCode: "BW", phoneCode: "+267", countryName: "Botswana" },
  { countryCode: "BR", phoneCode: "+55", countryName: "Brazil" },
  { countryCode: "BN", phoneCode: "+673", countryName: "Brunei" },
  { countryCode: "BG", phoneCode: "+359", countryName: "Bulgaria" },
  { countryCode: "BF", phoneCode: "+226", countryName: "Burkina Faso" },
  { countryCode: "BI", phoneCode: "+257", countryName: "Burundi" },
  { countryCode: "CV", phoneCode: "+238", countryName: "Cabo Verde" },
  { countryCode: "KH", phoneCode: "+855", countryName: "Cambodia" },
  { countryCode: "CM", phoneCode: "+237", countryName: "Cameroon" },
  { countryCode: "CA", phoneCode: "+1", countryName: "Canada" },
  {
    countryCode: "CF",
    phoneCode: "+236",
    countryName: "Central African Republic",
  },
  { countryCode: "TD", phoneCode: "+235", countryName: "Chad" },
  { countryCode: "CL", phoneCode: "+56", countryName: "Chile" },
  { countryCode: "CN", phoneCode: "+86", countryName: "China" },
  { countryCode: "CO", phoneCode: "+57", countryName: "Colombia" },
  { countryCode: "KM", phoneCode: "+269", countryName: "Comoros" },
  { countryCode: "CG", phoneCode: "+242", countryName: "Congo" },
  {
    countryCode: "CD",
    phoneCode: "+243",
    countryName: "Democratic Republic of the Congo",
  },
  { countryCode: "CK", phoneCode: "+682", countryName: "Cook Islands" },
  { countryCode: "CR", phoneCode: "+506", countryName: "Costa Rica" },
  { countryCode: "CI", phoneCode: "+225", countryName: "Ivory Coast" },
  { countryCode: "HR", phoneCode: "+385", countryName: "Croatia" },
  { countryCode: "CU", phoneCode: "+53", countryName: "Cuba" },
  { countryCode: "CW", phoneCode: "+599", countryName: "Curaçao" },
  { countryCode: "CY", phoneCode: "+357", countryName: "Cyprus" },
  { countryCode: "CZ", phoneCode: "+420", countryName: "Czech Republic" },
  { countryCode: "DK", phoneCode: "+45", countryName: "Denmark" },
  { countryCode: "DJ", phoneCode: "+253", countryName: "Djibouti" },
  { countryCode: "DM", phoneCode: "+1-767", countryName: "Dominica" },
  { countryCode: "DO", phoneCode: "+1-809", countryName: "Dominican Republic" },
  { countryCode: "EC", phoneCode: "+593", countryName: "Ecuador" },
  { countryCode: "EG", phoneCode: "+20", countryName: "Egypt" },
  { countryCode: "SV", phoneCode: "+503", countryName: "El Salvador" },
  { countryCode: "GQ", phoneCode: "+240", countryName: "Equatorial Guinea" },
  { countryCode: "ER", phoneCode: "+291", countryName: "Eritrea" },
  { countryCode: "EE", phoneCode: "+372", countryName: "Estonia" },
  { countryCode: "SZ", phoneCode: "+268", countryName: "Eswatini" },
  { countryCode: "ET", phoneCode: "+251", countryName: "Ethiopia" },
  { countryCode: "FJ", phoneCode: "+679", countryName: "Fiji" },
  { countryCode: "FI", phoneCode: "+358", countryName: "Finland" },
  { countryCode: "FR", phoneCode: "+33", countryName: "France" },
  { countryCode: "GF", phoneCode: "+594", countryName: "French Guiana" },
  { countryCode: "PF", phoneCode: "+689", countryName: "French Polynesia" },
  { countryCode: "GA", phoneCode: "+241", countryName: "Gabon" },
  { countryCode: "GM", phoneCode: "+220", countryName: "Gambia" },
  { countryCode: "GE", phoneCode: "+995", countryName: "Georgia" },
  { countryCode: "DE", phoneCode: "+49", countryName: "Germany" },
  { countryCode: "GH", phoneCode: "+233", countryName: "Ghana" },
  { countryCode: "GI", phoneCode: "+350", countryName: "Gibraltar" },
  { countryCode: "GR", phoneCode: "+30", countryName: "Greece" },
  { countryCode: "GL", phoneCode: "+299", countryName: "Greenland" },
  { countryCode: "GD", phoneCode: "+1-473", countryName: "Grenada" },
  { countryCode: "GP", phoneCode: "+590", countryName: "Guadeloupe" },
  { countryCode: "GU", phoneCode: "+1-671", countryName: "Guam" },
  { countryCode: "GT", phoneCode: "+502", countryName: "Guatemala" },
  { countryCode: "GN", phoneCode: "+224", countryName: "Guinea" },
  { countryCode: "GW", phoneCode: "+245", countryName: "Guinea-Bissau" },
  { countryCode: "GY", phoneCode: "+592", countryName: "Guyana" },
  { countryCode: "HT", phoneCode: "+509", countryName: "Haiti" },
  { countryCode: "HN", phoneCode: "+504", countryName: "Honduras" },
  { countryCode: "HK", phoneCode: "+852", countryName: "Hong Kong" },
  { countryCode: "HU", phoneCode: "+36", countryName: "Hungary" },
  { countryCode: "IS", phoneCode: "+354", countryName: "Iceland" },
  { countryCode: "IN", phoneCode: "+91", countryName: "India" },
  { countryCode: "ID", phoneCode: "+62", countryName: "Indonesia" },
  { countryCode: "IR", phoneCode: "+98", countryName: "Iran" },
  { countryCode: "IQ", phoneCode: "+964", countryName: "Iraq" },
  { countryCode: "IE", phoneCode: "+353", countryName: "Ireland" },
  { countryCode: "IL", phoneCode: "+972", countryName: "Israel" },
  { countryCode: "IT", phoneCode: "+39", countryName: "Italy" },
  { countryCode: "JM", phoneCode: "+1-876", countryName: "Jamaica" },
  { countryCode: "JP", phoneCode: "+81", countryName: "Japan" },
  { countryCode: "JO", phoneCode: "+962", countryName: "Jordan" },
  { countryCode: "KZ", phoneCode: "+7", countryName: "Kazakhstan" },
  { countryCode: "KE", phoneCode: "+254", countryName: "Kenya" },
  { countryCode: "KI", phoneCode: "+686", countryName: "Kiribati" },
  { countryCode: "KR", phoneCode: "+82", countryName: "South Korea" },
  { countryCode: "KW", phoneCode: "+965", countryName: "Kuwait" },
  { countryCode: "KG", phoneCode: "+996", countryName: "Kyrgyzstan" },
  { countryCode: "LA", phoneCode: "+856", countryName: "Laos" },
  { countryCode: "LV", phoneCode: "+371", countryName: "Latvia" },
  { countryCode: "LB", phoneCode: "+961", countryName: "Lebanon" },
  { countryCode: "LS", phoneCode: "+266", countryName: "Lesotho" },
  { countryCode: "LR", phoneCode: "+231", countryName: "Liberia" },
  { countryCode: "LY", phoneCode: "+218", countryName: "Libya" },
  { countryCode: "LI", phoneCode: "+423", countryName: "Liechtenstein" },
  { countryCode: "LT", phoneCode: "+370", countryName: "Lithuania" },
  { countryCode: "LU", phoneCode: "+352", countryName: "Luxembourg" },
  { countryCode: "MO", phoneCode: "+853", countryName: "Macau" },
  { countryCode: "MK", phoneCode: "+389", countryName: "North Macedonia" },
  { countryCode: "MG", phoneCode: "+261", countryName: "Madagascar" },
  { countryCode: "MW", phoneCode: "+265", countryName: "Malawi" },
  { countryCode: "MY", phoneCode: "+60", countryName: "Malaysia" },
  { countryCode: "MV", phoneCode: "+960", countryName: "Maldives" },
  { countryCode: "ML", phoneCode: "+223", countryName: "Mali" },
  { countryCode: "MT", phoneCode: "+356", countryName: "Malta" },
  { countryCode: "MH", phoneCode: "+692", countryName: "Marshall Islands" },
  { countryCode: "MR", phoneCode: "+222", countryName: "Mauritania" },
  { countryCode: "MU", phoneCode: "+230", countryName: "Mauritius" },
  { countryCode: "YT", phoneCode: "+262", countryName: "Mayotte" },
  { countryCode: "MX", phoneCode: "+52", countryName: "Mexico" },
  { countryCode: "FM", phoneCode: "+691", countryName: "Micronesia" },
  { countryCode: "MD", phoneCode: "+373", countryName: "Moldova" },
  { countryCode: "MC", phoneCode: "+377", countryName: "Monaco" },
  { countryCode: "MN", phoneCode: "+976", countryName: "Mongolia" },
  { countryCode: "ME", phoneCode: "+382", countryName: "Montenegro" },
  { countryCode: "MS", phoneCode: "+1-664", countryName: "Montserrat" },
  { countryCode: "MA", phoneCode: "+212", countryName: "Morocco" },
  { countryCode: "MZ", phoneCode: "+258", countryName: "Mozambique" },
  { countryCode: "MM", phoneCode: "+95", countryName: "Myanmar" },
  { countryCode: "NA", phoneCode: "+264", countryName: "Namibia" },
  { countryCode: "NR", phoneCode: "+674", countryName: "Nauru" },
  { countryCode: "NP", phoneCode: "+977", countryName: "Nepal" },
  { countryCode: "NL", phoneCode: "+31", countryName: "Netherlands" },
  { countryCode: "NC", phoneCode: "+687", countryName: "New Caledonia" },
  { countryCode: "NZ", phoneCode: "+64", countryName: "New Zealand" },
  { countryCode: "NI", phoneCode: "+505", countryName: "Nicaragua" },
  { countryCode: "NE", phoneCode: "+227", countryName: "Niger" },
  { countryCode: "NG", phoneCode: "+234", countryName: "Nigeria" },
  { countryCode: "NU", phoneCode: "+683", countryName: "Niue" },
  { countryCode: "NF", phoneCode: "+672", countryName: "Norfolk Island" },
  {
    countryCode: "MP",
    phoneCode: "+1-670",
    countryName: "Northern Mariana Islands",
  },
  { countryCode: "NO", phoneCode: "+47", countryName: "Norway" },
  { countryCode: "OM", phoneCode: "+968", countryName: "Oman" },
  { countryCode: "PK", phoneCode: "+92", countryName: "Pakistan" },
  { countryCode: "PW", phoneCode: "+680", countryName: "Palau" },
  { countryCode: "PS", phoneCode: "+970", countryName: "Palestine" },
  { countryCode: "PA", phoneCode: "+507", countryName: "Panama" },
  { countryCode: "PG", phoneCode: "+675", countryName: "Papua New Guinea" },
  { countryCode: "PY", phoneCode: "+595", countryName: "Paraguay" },
  { countryCode: "PE", phoneCode: "+51", countryName: "Peru" },
  { countryCode: "PH", phoneCode: "+63", countryName: "Philippines" },
  { countryCode: "PN", phoneCode: "+64", countryName: "Pitcairn Islands" },
  { countryCode: "PL", phoneCode: "+48", countryName: "Poland" },
  { countryCode: "PT", phoneCode: "+351", countryName: "Portugal" },
  { countryCode: "PR", phoneCode: "+1-787", countryName: "Puerto Rico" },
  { countryCode: "QA", phoneCode: "+974", countryName: "Qatar" },
  { countryCode: "RE", phoneCode: "+262", countryName: "Réunion" },
  { countryCode: "RO", phoneCode: "+40", countryName: "Romania" },
  { countryCode: "RU", phoneCode: "+7", countryName: "Russia" },
  { countryCode: "RW", phoneCode: "+250", countryName: "Rwanda" },
  { countryCode: "BL", phoneCode: "+590", countryName: "Saint Barthélemy" },
  { countryCode: "SH", phoneCode: "+290", countryName: "Saint Helena" },
  {
    countryCode: "KN",
    phoneCode: "+1-869",
    countryName: "Saint Kitts and Nevis",
  },
  { countryCode: "LC", phoneCode: "+1-758", countryName: "Saint Lucia" },
  { countryCode: "MF", phoneCode: "+590", countryName: "Saint Martin" },
  {
    countryCode: "PM",
    phoneCode: "+508",
    countryName: "Saint Pierre and Miquelon",
  },
  {
    countryCode: "VC",
    phoneCode: "+1-784",
    countryName: "Saint Vincent and the Grenadines",
  },
  { countryCode: "WS", phoneCode: "+685", countryName: "Samoa" },
  { countryCode: "SM", phoneCode: "+378", countryName: "San Marino" },
  {
    countryCode: "ST",
    phoneCode: "+239",
    countryName: "São Tomé and Príncipe",
  },
  { countryCode: "SA", phoneCode: "+966", countryName: "Saudi Arabia" },
  { countryCode: "SN", phoneCode: "+221", countryName: "Senegal" },
  { countryCode: "RS", phoneCode: "+381", countryName: "Serbia" },
  { countryCode: "SC", phoneCode: "+248", countryName: "Seychelles" },
  { countryCode: "SL", phoneCode: "+232", countryName: "Sierra Leone" },
  { countryCode: "SG", phoneCode: "+65", countryName: "Singapore" },
  { countryCode: "SX", phoneCode: "+1-721", countryName: "Sint Maarten" },
  { countryCode: "SK", phoneCode: "+421", countryName: "Slovakia" },
  { countryCode: "SI", phoneCode: "+386", countryName: "Slovenia" },
  { countryCode: "SB", phoneCode: "+677", countryName: "Solomon Islands" },
  { countryCode: "SO", phoneCode: "+252", countryName: "Somalia" },
  { countryCode: "ZA", phoneCode: "+27", countryName: "South Africa" },
  {
    countryCode: "GS",
    phoneCode: "+500",
    countryName: "South Georgia and the South Sandwich Islands",
  },
  { countryCode: "SS", phoneCode: "+211", countryName: "South Sudan" },
  { countryCode: "ES", phoneCode: "+34", countryName: "Spain" },
  { countryCode: "LK", phoneCode: "+94", countryName: "Sri Lanka" },
  { countryCode: "SD", phoneCode: "+249", countryName: "Sudan" },
  { countryCode: "SR", phoneCode: "+597", countryName: "Suriname" },
  { countryCode: "SZ", phoneCode: "+268", countryName: "Eswatini" },
  { countryCode: "SE", phoneCode: "+46", countryName: "Sweden" },
  { countryCode: "CH", phoneCode: "+41", countryName: "Switzerland" },
  { countryCode: "SY", phoneCode: "+963", countryName: "Syria" },
  { countryCode: "TW", phoneCode: "+886", countryName: "Taiwan" },
  { countryCode: "TJ", phoneCode: "+992", countryName: "Tajikistan" },
  { countryCode: "TZ", phoneCode: "+255", countryName: "Tanzania" },
  { countryCode: "TH", phoneCode: "+66", countryName: "Thailand" },
  { countryCode: "TL", phoneCode: "+670", countryName: "Timor-Leste" },
  { countryCode: "TG", phoneCode: "+228", countryName: "Togo" },
  { countryCode: "TK", phoneCode: "+690", countryName: "Tokelau" },
  { countryCode: "TO", phoneCode: "+676", countryName: "Tonga" },
  {
    countryCode: "TT",
    phoneCode: "+1-868",
    countryName: "Trinidad and Tobago",
  },
  { countryCode: "TN", phoneCode: "+216", countryName: "Tunisia" },
  { countryCode: "TR", phoneCode: "+90", countryName: "Turkey" },
  { countryCode: "TM", phoneCode: "+993", countryName: "Turkmenistan" },
  {
    countryCode: "TC",
    phoneCode: "+1-649",
    countryName: "Turks and Caicos Islands",
  },
  { countryCode: "TV", phoneCode: "+688", countryName: "Tuvalu" },
  { countryCode: "UG", phoneCode: "+256", countryName: "Uganda" },
  { countryCode: "UA", phoneCode: "+380", countryName: "Ukraine" },
  { countryCode: "AE", phoneCode: "+971", countryName: "United Arab Emirates" },
  { countryCode: "GB", phoneCode: "+44", countryName: "United Kingdom" },
  { countryCode: "US", phoneCode: "+1", countryName: "United States" },
  { countryCode: "UY", phoneCode: "+598", countryName: "Uruguay" },
  { countryCode: "UZ", phoneCode: "+998", countryName: "Uzbekistan" },
  { countryCode: "VU", phoneCode: "+678", countryName: "Vanuatu" },
  { countryCode: "VE", phoneCode: "+58", countryName: "Venezuela" },
  { countryCode: "VN", phoneCode: "+84", countryName: "Vietnam" },
  {
    countryCode: "VG",
    phoneCode: "+1-284",
    countryName: "British Virgin Islands",
  },
  {
    countryCode: "VI",
    phoneCode: "+1-340",
    countryName: "U.S. Virgin Islands",
  },
  { countryCode: "WF", phoneCode: "+681", countryName: "Wallis and Futuna" },
  { countryCode: "EH", phoneCode: "+212", countryName: "Western Sahara" },
  { countryCode: "YE", phoneCode: "+967", countryName: "Yemen" },
  { countryCode: "ZM", phoneCode: "+260", countryName: "Zambia" },
  { countryCode: "ZW", phoneCode: "+263", countryName: "Zimbabwe" },
];
